name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: install # will run `yarn install` command
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: jest --coverage # will run `jest` command


    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run ci:scripts
